/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: ["./index.html", "./src/**/*.{js,jsx,ts,tsx}"],
  theme: {
    extend: {
      colors: {
        "primary-fixed-dim": "#3cd7ff",
        "on-error": "#690005",
        "surface-container": "#1d2027",
        "surface-bright": "#363941",
        "error-container": "#93000a",
        "on-tertiary-fixed-variant": "#005236",
        "on-error-container": "#ffdad6",
        "on-background": "#e0e2ed",
        tertiary: "#00fdb0",
        "on-tertiary": "#003824",
        "tertiary-container": "#00dd9a",
        "surface-void": "#0D1117",
        "surface-variant": "#32353d",
        error: "#ffb4ab",
        "on-tertiary-fixed": "#002113",
        outline: "#859398",
        primary: "#a8e8ff",
        "on-primary-fixed": "#001f27",
        "surface-container-high": "#272a32",
        "surface-container-highest": "#32353d",
        "on-secondary-container": "#baaeff",
        "on-primary": "#003642",
        "on-secondary-fixed-variant": "#441cc8",
        "on-primary-fixed-variant": "#004e5f",
        "secondary-fixed": "#e5deff",
        "on-secondary": "#2e009c",
        "primary-container": "#00d4ff",
        "on-tertiary-container": "#005c3d",
        surface: "#10131b",
        "text-shadow": "#3D4F63",
        "on-surface-variant": "#bbc9cf",
        "surface-dim": "#10131b",
        "on-secondary-fixed": "#1a0063",
        "text-ghost": "#F0F4FF",
        "text-muted": "#8896A8",
        "secondary-container": "#4720ca",
        "inverse-on-surface": "#2d3038",
        "outline-variant": "#3c494e",
        "on-surface": "#e0e2ed",
        "surface-container-lowest": "#0b0e15",
        "tertiary-fixed": "#47ffb8",
        background: "#10131b",
        "surface-tint": "#3cd7ff",
        "secondary-fixed-dim": "#c9bfff",
        "on-primary-container": "#00586b",
        "tertiary-fixed-dim": "#00e29d",
        "border-steel": "#1E2A3A",
        "surface-container-low": "#181b23",
        "surface-panel": "#111827",
        "primary-fixed": "#b4ebff",
        "inverse-primary": "#00677e",
        "inverse-surface": "#e0e2ed",
        secondary: "#c9bfff"
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem"
      },
      spacing: {
        "margin-mobile": "20px",
        unit: "4px",
        "section-gap": "120px",
        "margin-desktop": "80px",
        gutter: "24px"
      },
      fontFamily: {
        "label-caps": ["Barlow Condensed"],
        "section-title": ["Syne"],
        "body-md": ["DM Sans"],
        "body-lg": ["DM Sans"],
        lead: ["DM Sans"],
        "display-xl": ["Orbitron"],
        "headline-hero-mobile": ["Orbitron"],
        "headline-hero": ["Orbitron"],
        code: ["JetBrains Mono"],
        "card-header": ["Syne"]
      },
      fontSize: {
        "label-caps": ["12px", { lineHeight: "16px", letterSpacing: "0.1em", fontWeight: "600" }],
        "section-title": ["32px", { lineHeight: "40px", fontWeight: "700" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        lead: ["20px", { lineHeight: "30px", fontWeight: "500" }],
        "display-xl": ["112px", { lineHeight: "120px", letterSpacing: "0.05em", fontWeight: "700" }],
        "headline-hero-mobile": ["48px", { lineHeight: "56px", fontWeight: "700" }],
        "headline-hero": ["72px", { lineHeight: "80px", fontWeight: "900" }],
        code: ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "card-header": ["24px", { lineHeight: "32px", fontWeight: "600" }]
      }
    }
  },
  plugins: []
};
